import { exec } from "child_process";
import fs from "fs";
import path from "path";

import { networkMapping as _networkMapping } from "../network-mapping/values";

export type NetworkMapping = Record<string, Record<string, `0x${string}`>>;

// Remove the as const
const networkMapping = _networkMapping as unknown as NetworkMapping;

const _file = "../network-mapping/values.ts";
const filePath = path.resolve(__dirname, _file);

export const setNetworkMapping = ({
  network,
  address,
  contract,
}: {
  network: string;
  contract: string;
  address: `0x${string}`;
}) => {
  network = network == "localhost" ? "hardhat" : network;

  networkMapping[network] = {
    ...networkMapping[network],
    [contract]: address,
  };

  const template = `/* Autogenerated file, take care when edit */
/* tslint:disable */
/* eslint-disable */ 
export const networkMapping =`;

  fs.writeFileSync(
    filePath,
    template + JSON.stringify(networkMapping, null, 2) + " as const;",
  );
  const cmd = "pnpx prettier -w " + filePath;

  console.log({ cmd });

  exec(cmd);
};
