/* Autogenerated file, take care when edit */
/* tslint:disable */
/* eslint-disable */
export const networkMapping = {
  hardhat: {
    MrCrypto: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    Lock: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  },
  goerli: {
    MrCrypto: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    Lock: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  },
} as const;
