/* Autogenerated file, take care when edit */
/* tslint:disable */
/* eslint-disable */
export const networkMapping = {
  hardhat: {
    Lock: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    MrCrypto: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
  },
} as const;
